version: '3.2'

services:
  b-elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: b-elastic
    # The single node is needed because else an error is thrown
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200