name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Install Docker
        uses: docker-practice/actions-setup-docker@master
      - uses: actions/checkout@v2
      - name: run
        run: cargo run